force-app/main/default/objects/BI_Metric__c/BI_Metric__c.object-meta.xml
<CustomObject>
    <description>Data points on important business information for standard SF objects - Lead, Contact, Account and Opportunity. Can be customized to support custom objects.</description>
    <label>BI Metric</label>
    <nameField>
        <displayFormat>BI-{0000}</displayFormat>
        <label>BI Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BI_Metric__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If this BI metric is related to a Lead, link here.</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Lead_BI_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BI_Metric__c/fields/Lifecycle_Field__c.field-meta.xml
<CustomField>
    <fullName>Lifecycle_Field__c</fullName>
    <description>Field for which we are tracking changes</description>
    <label>Lifecycle Field</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>StageName</fullName>
            </value>
            <value>
                <fullName>Status</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BI_Metric__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <description>New value for the field.</description>
    <label>New Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BI_Metric__c/fields/Owner_Id__c.field-meta.xml
<CustomField>
    <fullName>Owner_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user that owns the record at the time the record was updated.</description>
    <label>Record Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Owner_BI_Metrics2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BI_Metric__c/fields/Previous_Record__c.field-meta.xml
<CustomField>
    <fullName>Previous_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Previous Record for this BI Metric</description>
    <inlineHelpText>Previous value &amp; information for the BI metric for this record &amp; field.</inlineHelpText>
    <label>Previous Record</label>
    <referenceTo>BI_Metric__c</referenceTo>
    <relationshipName>BI_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BI_Metric__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>Text value of the source record id, to simplify queries</description>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BI_Metric__c/fields/Updating_User__c.field-meta.xml
<CustomField>
    <fullName>Updating_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user that actually updates the record, regardless of who owns the record.</description>
    <label>Updating User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Updating_BI_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BIMetricSortable_Test.cls
/**
 *	    BIMetricSortable_Test
 *	    Unit Tests for BIMetricSortable class
 *		@author Avodaas
 *		@date	Feb 2021
 **/
@isTest
private class BIMetricSortable_Test {
    
    @isTest static void testSortable(){
        TestBIModel.initData();
        List<String> statusVals = Avodaas_Apx.getPicklistValues('Lead', 'Status');
        BIMetricModel.createBIMetric('Status', statusVals[0], TestBIModel.myLead.Id, TestBIModel.myLead.OwnerId);
        Id metricId = BIMetricModel.getMostRecentBIRecord(TestBIModel.myLead.Id, 'Status');
        BI_Metric__c theMetric = [SELECT CreatedDate, Id FROM BI_Metric__c WHERE Lead__c = :TestBIModel.myLead.Id LIMIT 1];
        String statusVals2 = statusVals.size() > 1 ? statusVals[1] : statusVals[0];
        BI_Metric__c nextMetric = new BI_Metric__c(
            Lifecycle_Field__c = 'Status', 
            New_Value__c = statusVals2, 
            Previous_Record__c = metricId, 
            Owner_Id__c = TestBIModel.myLead.ownerId, 
            Updating_User__c = UserInfo.getUserId(), 
            Record_Id__c = String.valueOf(TestBIModel.myLead.Id)
        );
        insert nextMetric;
        BI_Metric__c clonedMetric = nextMetric.clone();
        insert clonedMetric;

        //now set the different created dates
        Test.setCreatedDate(metricId, System.today().addDays(-30));
        Test.setCreatedDate(clonedMetric.Id, System.today().addDays(-60));
        
        //create a list of wrapers 
        List<BIMetricSortable> sortMe = new List<BIMetricSortable>();
        sortMe.add(new BIMetricSortable(theMetric));
        sortMe.add(new BIMetricSortable(nextMetric));
        sortMe.add(new BIMetricSortable(clonedMetric));
        //sort them!
        sortMe.sort();       

    }
}