force-app/main/default/objects/BI_Metric__c/BI_Metric__c.object-meta.xml
<CustomObject>
    <description>Data points on important business information for standard SF objects - Lead, Contact, Account and Opportunity. Can be customized to support custom objects.</description>
    <label>BI Metric</label>
    <nameField>
        <displayFormat>BI-{0000}</displayFormat>
        <label>BI Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BI_Metric__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If this BI metric is related to a Lead, link here.</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Lead_BI_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BI_Metric__c/fields/Lifecycle_Field__c.field-meta.xml
<CustomField>
    <fullName>Lifecycle_Field__c</fullName>
    <description>Field for which we are tracking changes</description>
    <label>Lifecycle Field</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>StageName</fullName>
            </value>
            <value>
                <fullName>Status</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BI_Metric__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <description>New value for the field.</description>
    <label>New Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadBIModel_Test.cls
/**
 *  Lead_Test
 *    Unit tests for Lead class
 *    @author Avodaas
 *    @date  Feb 2021
 **/
@isTest
private class LeadBIModel_Test {
    @isTest static void testBIMetrics(){
        TestBIModel.initData();
        List<String> statusVals = Avodaas_Apx.getPicklistValues('Lead', 'Status');
        String status2 = (statusVals.size() > 1) ? statusVals[1] : statusVals[0];
        TestBIModel.myLead.Status = statusVals[0];
        TestBIModel.leadWithParams.Status = status2;
        Test.startTest();
        update new List<Lead>{TestBIModel.myLead, TestBIModel.leadWithParams};
        Test.stopTest();
        //verify that a new bi metric was created
        BI_Metric__c biMetric = [SELECT New_Value__c
                FROM BI_Metric__c 
                WHERE Lead__c = :TestBIModel.leadWithParams.Id and Lifecycle_Field__c  = 'Status' 
                        AND New_Value__c = :status2 LIMIT 1];
    }
    
}