force-app/main/default/objects/BI_Metric__c/BI_Metric__c.object-meta.xml
<CustomObject>
    <description>Data points on important business information for standard SF objects - Lead, Contact, Account and Opportunity. Can be customized to support custom objects.</description>
    <label>BI Metric</label>
    <nameField>
        <displayFormat>BI-{0000}</displayFormat>
        <label>BI Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BI_Metric__c/fields/Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Completed_Date__c</fullName>
    <description>Date that the record field was updated out of this value</description>
    <label>Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BI_Metric__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If this BI metric is related to a Lead, link here.</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Lead_BI_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BI_Metric__c/fields/Lifecycle_Field__c.field-meta.xml
<CustomField>
    <fullName>Lifecycle_Field__c</fullName>
    <description>Field for which we are tracking changes</description>
    <label>Lifecycle Field</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>StageName</fullName>
            </value>
            <value>
                <fullName>Status</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BI_Metric__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <description>New value for the field.</description>
    <label>New Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BI_Metric__c/fields/Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Owner_Name__c</fullName>
    <description>Name of the owner of the record at the time of this edit.</description>
    <label>Onwer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BI_Metric__c/fields/Owner_Role__c.field-meta.xml
<CustomField>
    <fullName>Owner_Role__c</fullName>
    <description>Owner Role at the time of update.</description>
    <label>Owner Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BI_Metric__c/fields/Previous_Record__c.field-meta.xml
<CustomField>
    <fullName>Previous_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Previous Record for this BI Metric</description>
    <inlineHelpText>Previous value &amp; information for the BI metric for this record &amp; field.</inlineHelpText>
    <label>Previous Record</label>
    <referenceTo>BI_Metric__c</referenceTo>
    <relationshipName>BI_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BIMetricModel_Test.cls
/**
 *	BIMetric_Test
 *	  Unit tests for BIMetric class
 *		@author Avodaas
 *		@date	Feb 2021
 **/
@isTest
private class BIMetricModel_Test {
    
    @isTest static void testBIMetrics(){
        //actual tests for bulk insertion are in LeadModel.
        //this is only to test the single insertion method
        //TestBIModel.initData gives code coverage
        Test.startTest();
        TestBIModel.initData();
        List<String> statusVals = Avodaas_Apx.getPicklistValues('Lead', 'Status');
        String statusVal2 = statusVals.size() > 1 ? statusVals[1] : '';
        BIMetricModel.createBIMetric('Status', statusVals[0], TestBIModel.myLead.Id, TestBIModel.myLead.OwnerId);
        BIMetricModel.createBIMetric('Status', statusVal2, TestBIModel.myLead.Id, TestBIModel.myLead.OwnerId);
        TestBIModel.case1.OwnerId = TestBIModel.supportQueueGroup.Id;
        update TestBIModel.case1;
        Test.stopTest();
        //try to select the metric that should have been created by the above call
        //if it wasn't created, the test fails with no rows to assign error
        BI_Metric__c biMetric = [SELECT Id, Previous_Record__r.Completed_Date__c, Owner_Name__c, Owner_Role__c
                FROM BI_Metric__c 
                WHERE Lead__c = :TestBIModel.myLead.Id and Lifecycle_Field__c  = 'Status' AND New_Value__c = :statusVal2
                LIMIT 1];
        User leadOwner = [SELECT Name, UserRole.Name FROM User WHERE Id = :TestBIModel.user1.Id];
        //validate that the previous one was completed, owner info set.
        System.assertEquals(System.today(), biMetric.Previous_Record__r?.Completed_Date__c);
        System.assertEquals(leadOwner.Name, biMetric.Owner_Name__c);
        System.assertEquals(leadOwner.UserRole.Name, biMetric.Owner_Role__c);

        //code coverage for bad object names 
        List<BIMetricModel.BIFieldWrapper> fields = BIMetricModel.getFieldsToTrackForSObject('A bad object');
        System.assertEquals(null, fields);
        ///create via wrappers
        List<BIMetricModel.BIUpdateWrapper> wrappers = new List<BIMetricModel.BIUpdateWrapper>();
        wrappers.add(new BIMetricModel.BIUpdateWrapper(TestBIModel.opp1.Id, 'Sales_Qualified_Lead_Date__c', TestBIModel.user1.Id, System.today(), null));
        wrappers.add(new BIMetricModel.BIUpdateWrapper(TestBIModel.vet1.Id, 'Email', TestBIModel.user1.Id, 'test@test.com', null));
        wrappers.add(new BIMetricModel.BIUpdateWrapper(TestBIModel.opp1.Id, 'CreatedDate', TestBIModel.user1.Id, System.now(), null));
        wrappers.add(new BIMetricModel.BIUpdateWrapper(TestBIModel.opp1.Id, 'Amount', TestBIModel.user1.Id, 250.00, null));
        BIMetricModel.createBIMetrics(wrappers);
        wrappers.clear();
        //code coverage for more than one metric per object & field, and with data types
        wrappers.add(new BIMetricModel.BIUpdateWrapper(TestBIModel.opp1.Id, 'Sales_Qualified_Lead_Date__c', TestBIModel.user1.Id, System.today().addDays(3), 'DATE'));
        wrappers.add(new BIMetricModel.BIUpdateWrapper(TestBIModel.opp1.Id, 'CreatedDate', TestBIModel.user1.Id, System.now().addHours(3), 'DATETIME'));
        wrappers.add(new BIMetricModel.BIUpdateWrapper(TestBIModel.opp1.Id, 'Amount', TestBIModel.user1.Id, 350.00, 'CURRENCY'));
        BIMetricModel.createBIMetrics(wrappers);
        wrappers.clear();
        wrappers.add(new BIMetricModel.BIUpdateWrapper(TestBIModel.opp1.Id, 'Sales_Qualified_Lead_Date__c', TestBIModel.user1.Id, System.today().addDays(4), 'DATE'));
        wrappers.add(new BIMetricModel.BIUpdateWrapper(TestBIModel.opp1.Id, 'CreatedDate', TestBIModel.user1.Id, System.now().addHours(4), 'DATETIME'));
        wrappers.add(new BIMetricModel.BIUpdateWrapper(TestBIModel.opp1.Id, 'Amount', TestBIModel.user1.Id, 360.00, 'CURRENCY'));
        System.enqueueJob(new QueueableBIMetric(wrappers));
    }
}