force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Track status of individual accounts</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
            <value>
                <fullName>In Pipeline</fullName>
            </value>
            <value>
                <fullName>Current Customer</fullName>
            </value>
            <value>
                <fullName>Attrited Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BI_Metric__c/BI_Metric__c.object-meta.xml
<CustomObject>
    <description>Data points on important business information for standard SF objects - Lead, Contact, Account and Opportunity. Can be customized to support custom objects.</description>
    <label>BI Metric</label>
    <nameField>
        <displayFormat>BI-{0000}</displayFormat>
        <label>BI Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BI_Metric__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If the BI metric is for an account, link here</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_BI_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BI_Metric__c/fields/Lifecycle_Field__c.field-meta.xml
<CustomField>
    <fullName>Lifecycle_Field__c</fullName>
    <description>Field for which we are tracking changes</description>
    <label>Lifecycle Field</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>StageName</fullName>
            </value>
            <value>
                <fullName>Status</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BI_Metric__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <description>New value for the field.</description>
    <label>New Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Avodaas_AccountModel_Test.cls
/**
 *  Account_Test
 *    Unit tests for Account class
 *    @author Avodaas
 *    @date  Feb 2021
 **/
@isTest
private class Avodaas_AccountModel_Test {
    @isTest static void testBIMetrics(){
        TestBIModel.initData();
        List<String> statusVals = Avodaas_Apx.getPicklistValues('Account', 'Account_Status__c');
        TestBIModel.clinic1.Account_Status__c = statusVals[0];
        Test.startTest();
        update TestBIModel.clinic1;
        Test.stopTest();
        //verify that a new bi metric was created
        BI_Metric__c biMetric = [SELECT New_Value__c
                FROM BI_Metric__c 
                WHERE Account__c = :TestBIModel.clinic1.Id and Lifecycle_Field__c  = 'Account_Status__c' 
                        AND New_Value__c = :statusVals[0] LIMIT 1];
    }
    
}